/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface GridCalendarComponent {}
  interface GridCalendarComponentAttributes extends StencilHTMLAttributes {}

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface EmployeesPage {}
  interface EmployeesPageAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'GridCalendarComponent': Components.GridCalendarComponent;
    'AppRoot': Components.AppRoot;
    'EmployeesPage': Components.EmployeesPage;
  }

  interface StencilIntrinsicElements {
    'grid-calendar-component': Components.GridCalendarComponentAttributes;
    'app-root': Components.AppRootAttributes;
    'employees-page': Components.EmployeesPageAttributes;
  }


  interface HTMLGridCalendarComponentElement extends Components.GridCalendarComponent, HTMLStencilElement {}
  var HTMLGridCalendarComponentElement: {
    prototype: HTMLGridCalendarComponentElement;
    new (): HTMLGridCalendarComponentElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLEmployeesPageElement extends Components.EmployeesPage, HTMLStencilElement {}
  var HTMLEmployeesPageElement: {
    prototype: HTMLEmployeesPageElement;
    new (): HTMLEmployeesPageElement;
  };

  interface HTMLElementTagNameMap {
    'grid-calendar-component': HTMLGridCalendarComponentElement
    'app-root': HTMLAppRootElement
    'employees-page': HTMLEmployeesPageElement
  }

  interface ElementTagNameMap {
    'grid-calendar-component': HTMLGridCalendarComponentElement;
    'app-root': HTMLAppRootElement;
    'employees-page': HTMLEmployeesPageElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
