/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface GridCalendar {}
  interface GridCalendarAttributes extends StencilHTMLAttributes {}

  interface SelectMenu {
    'model': any[];
    'selectedValue': string;
  }
  interface SelectMenuAttributes extends StencilHTMLAttributes {
    'model'?: any[];
    'onSelectedChange'?: (event: CustomEvent<string>) => void;
    'selectedValue'?: string;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface HolidaysPage {}
  interface HolidaysPageAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'GridCalendar': Components.GridCalendar;
    'SelectMenu': Components.SelectMenu;
    'AppRoot': Components.AppRoot;
    'HolidaysPage': Components.HolidaysPage;
  }

  interface StencilIntrinsicElements {
    'grid-calendar': Components.GridCalendarAttributes;
    'select-menu': Components.SelectMenuAttributes;
    'app-root': Components.AppRootAttributes;
    'holidays-page': Components.HolidaysPageAttributes;
  }


  interface HTMLGridCalendarElement extends Components.GridCalendar, HTMLStencilElement {}
  var HTMLGridCalendarElement: {
    prototype: HTMLGridCalendarElement;
    new (): HTMLGridCalendarElement;
  };

  interface HTMLSelectMenuElement extends Components.SelectMenu, HTMLStencilElement {}
  var HTMLSelectMenuElement: {
    prototype: HTMLSelectMenuElement;
    new (): HTMLSelectMenuElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLHolidaysPageElement extends Components.HolidaysPage, HTMLStencilElement {}
  var HTMLHolidaysPageElement: {
    prototype: HTMLHolidaysPageElement;
    new (): HTMLHolidaysPageElement;
  };

  interface HTMLElementTagNameMap {
    'grid-calendar': HTMLGridCalendarElement
    'select-menu': HTMLSelectMenuElement
    'app-root': HTMLAppRootElement
    'holidays-page': HTMLHolidaysPageElement
  }

  interface ElementTagNameMap {
    'grid-calendar': HTMLGridCalendarElement;
    'select-menu': HTMLSelectMenuElement;
    'app-root': HTMLAppRootElement;
    'holidays-page': HTMLHolidaysPageElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
